### ISSUE TITLE
go get -u go.uber.org/zap download failed

### ISSUE THREAD

**Issue by QueryStyle** [cosmos-gg/meq#86]
package go.uber.org/zap: unrecognized import path "go.uber.org/zap" (https fetch: Get https://go.uber.org/zap?go-get=1: dial tcp 104.28.0.50:443: i/o timeout)

**Comment by sunface** [comment]
sorry for that , maybe there will be two solutions: 1. you need a local proxy for accessing the unreachable website 2. Maybe I  will make a vendor sonn

**Comment by sunface** [comment]
some vendor dependencies added,problem resolved

**Comment by QueryStyle** [comment]
thx
